### ISSUE TITLE
Displayed plot size in tutorials

### ISSUE THREAD

**Issue by Hrovatin** [scverse/scanpy-tutorials#115]
In the [visualization tutorials](https://scanpy-tutorials.readthedocs.io/en/latest/plotting/advanced.html) the plots are rendered to a box of predefined size/shape and plots are not properly displayed - they get the correct size only after clicking on the plots to open in a separate window. This is problematic for the tutorial as we want to show how to properly align/size plots and the current layout makes it seem like plots are not properly sized. 
See the example below that is completely squashed:
<img width="660" alt="image" src="https://github.com/scverse/scanpy-tutorials/assets/47607471/0ecae3f8-d009-46c9-9bcc-941bb6512367">
While the image opened in a separate tab looks normal:
<img width="138" alt="image" src="https://github.com/scverse/scanpy-tutorials/assets/47607471/1b15b270-55fb-49b6-88b9-0babb2b5e13e">

**Comment by flying-sheep** [comment]
Isaac made the scanpy docs the canonical location for these, and the plots do work there! https://scanpy.readthedocs.io/en/stable/tutorials/plotting/advanced.html

I’ll make sure banners are shown here with the canonical location.
