### ISSUE TITLE
Run tutorial on Google Cloud VM instance 

### ISSUE THREAD

**Issue by yinshanfang** [scverse/scanpy-tutorials#40]
Hello, I'm a new user to run the scanpy-tutorials on Google cloud vm instance. I can't get figure when I run it. For example, when I run "sc.pl.highest_expr_genes(adata, n_top=20, )", it just finished, but no figure showing as expected. I know it's not an issue of scanpy, but do you have any experience and suggestions? Thank you so much.

**Comment by flying-sheep** [comment]
This should solve it: https://stackoverflow.com/questions/73690732/how-do-i-get-my-python-matplotlib-object-to-show-in-gcp-terminal
