### ISSUE TITLE
Analyzing CITE-seq data contains internal comments

### ISSUE THREAD

**Issue by andreas-wilm** [scverse/scanpy-tutorials#41]
Hello there, thanks for the amazing Scanpy tutorials!

The [CITE-seq tutorials](https://scanpy-tutorials.readthedocs.io/en/multiomics/cite-seq/pbmc5k.html) contains a number of internal comments, which you might want to hide. Here are a few examples:

> We still need to explain the function here. I’m happy if we add it to the first tutorial, too (I know you did it already at some point, but I didn’t want to let go of the simpler naming scheme back then; now I’d be happy to transition.)

> TODO: I would like to include some justification for the change in normalization. It definitley has a much different distribution than transcripts. I think this could be shown through the qc plots, but it’s a huge pain to move around these matplotlib plots. This might be more appropriate for the in-depth guide though.

> Agreed! But, having an explanation of the two images below is also a good first step. Also nice to contrast it with the corresponding RNA distributions.

> Discuss that this here is a different normalization.

> Yes, would be great to the see the QC plots, here, too. Are cells with low counts etc. weird only on the RNA level or also on the protein level? It’d be nice to see the QC plots side-by-side between RNA and protein, I’d say.

**Comment by Zethson** [comment]
We removed the CITE-seq tutorials and recommend that people use https://github.com/scverse/muon
