### ISSUE TITLE
combining protein and RNA

### ISSUE THREAD

**Issue by vladie0** [scverse/scanpy-tutorials#42]
Dear developers, 

I'm trying to follow your tutorial in combining for CITE-seq but fail to recombine both datasets, protein & RNA back into one object.
This might have to do with processing each set differently (filtering cells, genes) and trying to recombine again. How can this be facilitated or in which manner can I process protein & RNA and recombine both files to visualize?

Kind Regards

**Comment by flying-sheep** [comment]
Sorry for not getting back to you back then, but I think there need to be more details for us to be able to help.

You probably find more help on the discourse or zulip, linked on https://scverse.org/
