### ISSUE TITLE
cell type annotation problem

### ISSUE THREAD

**Issue by ryrl9703** [scverse/scanpy-tutorials#44]
When I ran the code in  clustering of the tutorials, all were well, except the "sc.pl.umap(adata, legend_loc='on data', title='', frameon=False, save='.pdf', color='leiden')". It reports that 'Float64Index' object has no attribute 'add_categories', how should i solve this problem
![微信图片_20210831165057](https://user-images.githubusercontent.com/87462884/131472841-ca813f68-c3c2-49df-aeae-628e14d0eda0.png)

**Comment by Koncopd** [comment]
Hi, it seems to be a pandas problem. What pandas version do you use? You could try downgrading pandas for now.

**Comment by ryrl9703** [comment]
> Hi, it seems to be a pandas problem. What pandas version do you use? You could try downgrading pandas for now.

pandas=1.3.2. Thank you very much
