### ISSUE TITLE
KeyError: 'rank_genes_groups'

### ISSUE THREAD

**Issue by jwweii** [scverse/scanpy-tutorials#47]
I just practiced scanpy by the 3K PBMC tutorial. Yet, I encountered an error as following: 

![Rank genes groups Error](https://user-images.githubusercontent.com/92627943/146681658-e728306b-3aa3-4870-9372-dae8497540a1.jpg)

How to solve this problem?

**Comment by Zethson** [comment]
Dear @jwweii 

we would need the full code that you ran to allow us to assess where things went wrong. Since this issue is already half a year old I will allow myself to close it. Feel free to reopen if this issue persists!
