### ISSUE TITLE
ipynb that can be run as a single pipeline from start to finish

### ISSUE THREAD

**Issue by sylestiel** [scverse/scanpy-tutorials#53]
@ivirshup 
Hi!

Is there a SINGLE ipynb to run preprocessing, core plotting and trajectory as one pipeline in jupyter notebook?

Also are there provisions to subset clusters and analyze further?

Thanks!

**Comment by Zethson** [comment]
This might be what you are looking for https://github.com/theislab/single-cell-tutorial/blob/master/latest_notebook/Case-study_Mouse-intestinal-epithelium_1906.ipynb
