### ISSUE TITLE
3k PBMCs tutorial: neighborhood graph scanpy vs. Seurat

### ISSUE THREAD

**Issue by p-lombard** [scverse/scanpy-tutorials#72]
Hello! 

I have been trying to translate a colleague's Seurat-based R code to scanpy/Python and have been using the PBMC 3k guided tutorials from each as a reference for basic preprocessing workflow. Let me know if this question would be better suited for mainstream scanpy, but I was having trouble understanding the translation between Seurat `FindNeighbors()` and scanpy `pp.neighbors()` based on the docs. 

In [Seurat's 3k PBMCs tutorial](https://satijalab.org/seurat/articles/pbmc3k_tutorial.html), they use JackStraw to determine the dimensionality of the data (first 10 PCs) and then construct the KNN graph with that dimensionality as a param of the  `FindNeighbors()` function:
`pbmc <- FindNeighbors(pbmc, dims = 1:10)`

Based on the `sc.pp.neighbors()` documentation, I assumed that scanpy's **n_pcs** param would be equivalent to the `FindNeighbors()` **dims** param, but in the [scanpy 3k PBMCs tutorial](https://scanpy-tutorials.readthedocs.io/en/latest/pbmc3k.html) it reads:

> Let us compute the neighborhood graph of cells using the PCA representation of the data matrix. You might simply use default values here. For the sake of reproducing Seurat’s results, let’s take the following values.
`sc.pp.neighbors(adata, n_neighbors=10, n_pcs=40)` 

If we wanted to reproduce Seurat's results from their tutorial, wouldn't we want to set n_pcs = 10 to include the first 10 PCs when creating the neighborhood graph? I just wanted to clarify that n_pcs is the correct scanpy parameter for setting the number of PCs included for the KNN graph. 

Thank you!

Phoebe

**Comment by flying-sheep** [comment]
Analysis isn’t sensitive to the number of PCs:

> We chose 10 here, but encourage users to consider the following:
> 
> - […]
> - We encourage users to repeat downstream analyses with a different number of PCs (10, 15, or even 50!). As you will observe, the results often do not differ dramatically.
> - We advise users to err on the higher side when choosing this parameter. For example, performing downstream analyses with only 5 PCs does significantly and adversely affect results.

Read here for more discussion on the topic: https://github.com/scverse/scanpy/issues/872#issuecomment-559334707

If you have strong feelings about this, feel free to continue that discussion!

I hope that helped clear things up!

**Comment by p-lombard** [comment]
Thank you!
