### ISSUE TITLE
Use sklearn-ann in "alternative knn libraries" tutorial?

### ISSUE THREAD

**Issue by ivirshup** [scverse/scanpy-tutorials#90]
@flying-sheep, should we point out (and maybe use) [`sklearn-ann`](https://sklearn-ann.readthedocs.io/en/latest/) in the tutorial you added?

**Comment by ivirshup** [comment]
I feel like the definition of the `Annoy` class should go into the docs for sklearn-ann either way

**Comment by flying-sheep** [comment]
It’s mentioned and linked twice. I didn’t directly use it because that way it’s easier to explain how the class has to look.
