### ISSUE TITLE
Scale data in Visium tutorial? #question

### ISSUE THREAD

**Issue by Jieran-S** [scverse/scanpy-tutorials#93]
Couldn't find anything in exisitng/closed issue so I asked here.

Thank you for implementing those concise yet comprehensive tutorials. In [Visium data processing tutorial](https://scanpy-tutorials.readthedocs.io/en/latest/spatial/basic-analysis.html), no scaling was done before PCA is conducted. Is there any specific reason for skipping this step? 

Thanks in advance for the answer!

**Comment by flying-sheep** [comment]
The best place for questions is probably https://discourse.scverse.org/

That being said, I think scaling isn’t done commonly anymore because it densifies sparse data (which is heavy on the memory), and many analysis tools these days don’t need scaled data to work.
